id:
  cache:
    capacity: 40
    trigger: 20
    initWaitTimeMs: 5000
  zk:
    -
      namespace: id
      connection: 127.0.0.1:2181
      sessionTimeoutMs: 10000
      connectionTimeoutMs: 10000
    -
      namespace: id
      connection: 127.0.0.1:2181
      sessionTimeoutMs: 10000
      connectionTimeoutMs: 10000
server:
  port: 8888